### ISSUE TITLE
How does Rack work?

### ISSUE THREAD

**Issue by acant** [kwruby/kwruby.ca#12]
Walk through how the [Rack](https://rack.github.io/) framework works. 
* how Rack middle ware works
* could consider how Rails and its middleware's interact with Rack

**Comment by mulder** [comment]
@acant you looking for speakers?  I'm an engineering lead @ Shopify.  We just moved into town a little while back.  Would love to connect with the local ruby community out here!

**Comment by acant** [comment]
@mulder We are definitely looking for speakers! We have a [meeting on Tuesday](http://www.meetup.com/kw-ruby-on-rails/events/220822362/) if any of your engineers are would like to attend.
Are you interested in a Rack presentation?

**Comment by mulder** [comment]
@acant I heard about the metope tonight.  Unfortunately I'm Ottawa bound.  I'll ask around to see if anyone else is free to make it out.

I love rack and would gladly do a presentation.  Just let me know how long you want it to be and how much of that time you want geared towards beginners, intermediate and advanced.

I could also speak on Deploying, API's, Sprockets, CI, ActiveJob, Rails Engines pretty much anything ruby/rails/rails-core related.  Also more general software eng topics.

**Comment by acant** [comment]
@mulder I hope you Ottawa trip when well!
A rack presentation would be great. 
We start the meetings around 7pm, so an hour-ish presentation + time for questions, and some mingling after wards, and we are finished between 930 and 1000. And I'm sure you could go a little longer if you needed to.

We usual have a mix of Ruby beginners and those with more experience. If you went 50/50, between basic explanation and some more in depth details, I think that would be good.

When would you like to present? Next month, May 19th, is open at the moment.
June 16th and July 21st, would be the next dates, if those work better.

As for you other possible topics, any of those would be weclome. I think a few you mentioned are already listed in other Issues. ActiveJobs in particular would be interesting given its relative newness.

Thanks again for volunteering. I am looking forward to the Rack presentation!

**Comment by acant** [comment]
@mulder will be presenting on Rack on May 19th. You can find the details and RSVP [here](http://www.meetup.com/kw-ruby-on-rails/events/222320687/).
