### ISSUE TITLE
Project/Workshop night

### ISSUE THREAD

**Issue by acant** [kwruby/kwruby.ca#22]
This could be a night without a presentation to help each other with our projects. Laptops would be out, and hopefully code would be read and written. Many of the developers who have joined in Meetup have indicated that they are new to Ruby, so this might present a good venue for providing then with assistance.

Possible formats:
- round table with laptops, and members throwing out problems they need help with
- presenting gems/projects people would like help on and get started contributing
- match junior and advanced developers for mentoring

Examples of others doing something like this:
- locally, [WatPy](http://www.watpy.ca) has a weekly Python workshop every Monday
- and [Bostonrb](http://bostonrb) has a [project night](http://bostonrb.org/project_night)

**Comment by JECurrie** [comment]
Hi Andrew:   would be very interested.  Right now I am doing exercism.io exercises and going through Eric's notes on "intro-to-tdd".Thanks.Joan.

**Comment by Ellcat** [comment]
Thanks again for the meetup tonight. I'd be interested in a workshop.

**Comment by acant** [comment]
An interesting possibility for a workshop might be working on some open source projects. Evening on big-ish projects there are frequently small tasks that we could get started on. 

Some possibilities:
* [Rails](http://rubyonrails.org/), kind of the big obvious one
* [Discourse](https://www.discourse.org/), again a big project and I think there are some contributers in the area
* any of the projects that support [RubyGems](http://guides.rubygems.org/contributing/), 
* cleaning up gems which projects that we're working on depend upon

And possible smallish activities:
* writing/updating documentation
* applying rubocop or other linters to improve code quality
* writing tests/specs
* re-producing existing bug reports
* cleaning up Ruby warnings

**Comment by acant** [comment]
Would the [guard](https://github.com/guard/guard) project be interesting? It would be a none web project, which is always looking for more contributors. It is also broken into multiple gems, which might also make contributing a little easier.

**Comment by JECurrie** [comment]
I would be interested in this.  Thanks Andrew.

**Comment by acant** [comment]
We are going to try the workshop out in October 2017.
RSVP https://www.meetup.com/kw-ruby-on-rails/events/234273702/

**Comment by JECurrie** [comment]
"Would the guard <https://github.com/guard/guard> project be interesting?
It would be a none web project, which is always looking for more
contributors."
You mean " non-Web-based application"?
http://smallbusiness.chron.com/disadvantages-building-nonwebbased-application-40347.html

Cheers, Joan.

**Comment by acant** [comment]
> You mean " non-Web-based application"?
> http://smallbusiness.chron.com/disadvantages-building-nonwebbased-application-40347.html

:) non-web was definitely what I meant, and I have updated my comment.
Thanks Joan.

**Comment by JECurrie** [comment]
so...  I am starting learning the guard project.  I am interested in the
management of
the guard.  My background is in physics (started Fortran 1981), did grad
work in
physical oceanography (fluid dynamics), stroked in 1989, did work as
speech-language
technician...  so fluid dynamics, speech-language work and computer work.

Cheers Andrew.
Joan.

**Comment by acant** [comment]
This post about contributing to the Ruby project has some useful resources:
http://www.sihui.io/how-to-contribute-to-ruby/

**Comment by acant** [comment]
OpenStreetMaps main website is a Rails application
https://github.com/openstreetmap/openstreetmap-website

Given, that this is a long lived application and probably pretty high usage, this could make an interesting place to contribute. 
They have lots of issues, so helping with triage could be a place to start.

**Comment by JECurrie** [comment]
Thanks Andrew. Joan.

**Comment by acant** [comment]
Another idea: the month after a presentation we could try working on the project which was presented, maybe help with some issues, or at least get the test suite running.
This might be a good introduction to the tools for beginners.
And the more experienced developers get working on projects they might light to contribute to.

**Comment by JECurrie** [comment]
Great idea.

**Comment by movermeyer** [comment]
@acant, I love the idea of helping out the project you learned about in the previous meetup.

However, unless you are being careful in the way that you pick speakers, you will not always have an easy-to-contribute-to, open-source project. This [podcast I just listened to](https://changelog.com/rfc/10) talks about this a bit.

I wonder if a shorter time-frame than 1 month would be better. The following week?

**Comment by RhinoCan** [comment]
I think that would be a good topic, although I'm a lot more likely to look over someone's else's shoulder to learn more about Rails than to write actual code myself yet. (I've gotten sidetracked from learning Rails and am focusing on Android development - and PHP - for the moment but I'm still keen to get started on Rails once I'm over the main part of the Android learning curve.)

**Comment by acant** [comment]
@movermeyer I am interested in trying the one week option. The Gitlab presentation is on July 17, then we could try doing a workshop on July 24th. (...and wow July has a lot of weeks) 

Even getting the test suite compiling might be a good learning experience. Most of us, certainly me, have probably only compiled or runs test for a teeny, tiny amount of the software we use.

**Comment by acant** [comment]
@RhinoCan I think that looking over someones should or pair programming would be a great use of workshops. It could help beginners get started and more experienced developers practice their teaching/mentoring skills.
And if you walks about with a working development environment, that will make it easier of to contributed in various ways.

**Comment by acant** [comment]
Closing this issue since we have been doing workshop nights, and they seem to have been working.
Our next one is on April 16 https://www.meetup.com/kw-ruby-on-rails/events/259765690/
