### ISSUE TITLE
Using sidekiq to to run jobs with Rails

### ISSUE THREAD

**Issue by acant** [kwruby/kwruby.ca#29]
This could be pair with a DelayedJobs presentation #2, to compare and contrast.
[sidekiq](http://sidekiq.org/) is a threaded job running system which is open, and has commercial support.

**Comment by acant** [comment]
@smaclell @TCampaigne a few months ago we discussed a sidekiq presentation. Would anyone at Vidyard be interested?

**Comment by acant** [comment]
@wcurtis someone at the last meeting mentioned that Smile is using sidekiq too.

**Comment by wcurtis** [comment]
Can confirm. We ❤️ Sidekiq.

**Comment by smaclell** [comment]
Let me double check with the Crew and get back to you.

**Comment by Kuresov** [comment]
I would be up for presenting on this unless someone else is especially interested. @wcurtis If you'd like to get up there as well, I'd be happy to work with you on it!

**Comment by acant** [comment]
Happy New Year!
@Kuresov @wcurtis would you like to present on 2018-05-15? 
Its a great topic and you will help me fill in my "KWRuby 2018 Meetings Bingo Card". :)

**Comment by acant** [comment]
ping @Kuresov and @wcurtis about if either of you would like to present on sidekiq in in May?

**Comment by Kuresov** [comment]
Hey @acant I am still up for May!

**Comment by acant** [comment]
Awesome @Kuresov I will schedule the meetup today, and I will add a link here.
Thanks in advance! I am never used sidekiq so I am looking forward to learning more about it.

**Comment by acant** [comment]
@Kuresov you have been scheduled for May 15th!
https://www.meetup.com/kw-ruby-on-rails/events/247025010/

I have written a very simple description and title. If you can give me something more detailed I will updated it. And if you could send me a brief bio for yourself, that would be much appreciated.

**Comment by acant** [comment]
Closing this issue since the presentation is upcoming.
