### ISSUE TITLE
Webpack and Rails

### ISSUE THREAD

**Issue by acant** [kwruby/kwruby.ca#30]
[Webpack](https://webpack.js.org/) is a new standard for packaging up assets to be sent to the browser. This includes assets like CSS, images, and Javascript.

It has already been included in [Rails5.1](http://weblog.rubyonrails.org/2017/2/23/Rails-5-1-beta1/) and would be interesting to learn more about.

**Comment by acant** [comment]
@VadimBrodsky @Illianthe would either of you be interested in doing a webpack presentation for KWRuby?

**Comment by Illianthe** [comment]
I haven't had the chance to play with webpacker but could probably throw together something depending on what people are interested in.

**Comment by Illianthe** [comment]
I asked Vadim and he mentioned that he'd be interested in doing this as well. Ideally we'd have a bit more lead time but it should be fine assuming we're able to finalize a space.

**Comment by acant** [comment]
Sorry for my delay in responding. And given that why don't we scheduled a little farther in the future. :)
How about January 16th?
(December 19th is also open if January does not work, but I usually skip or arrange a social night since it is so close to the holidays.)

**Comment by acant** [comment]
@Illianthe and @VadimBrodsky will be presenting on webpack on March 20th 2018.
You can see details and RSVP at https://www.meetup.com/kw-ruby-on-rails/events/247023400/

**Comment by VadimBrodsky** [comment]
Here is the repo from the example app -- https://github.com/Illianthe/mechhead
