### ISSUE TITLE
Automate the deployment of kwruby.ca

### ISSUE THREAD

**Issue by acant** [kwruby/kwruby.ca#35]
It would make it easier to update the site, if it automatically tested and deployed it when changes are pushed to the master branch. I have implemented this kind of system on Gitlab, but I have never done it on at Github.

I did find some articles on how to to it with Github pages and Jekyl:
* https://jahed.io/2015/05/31/automating-deployments-to-github-pages-with-middleman-and-travis-ci/
* https://pietvanzoen.com/blog/automated-middleman-deploy-to-github-pages/

I suspect something similar would work with middleman.

**Comment by lucasprag** [comment]
I can work on this next weekend if that is ok 👍

**Comment by lucasprag** [comment]
Hi @acant Thanks for inviting me to the organization. I hope to contribute more =)

I didn't forget about this issue, I'm still working on it on my free time.

Because the gems are really outdated the first thing I'm doing is to upgrade all them.
I'm half way of finishing it and I think it's going to be valuable for future contributions. I'm going to submit a PR about this upgrade first.

Thanks and see you at the next meetup =)

**Comment by acant** [comment]
Awesome thanks for the work @lucasprag. See on on Tuesday.

**Comment by lucasprag** [comment]
There is a github action for doing automating deploy with middleman to github pages: https://github.com/marketplace/actions/github-pages-deploy

Could you sign up for the beta please? @acant 
https://github.com/features/actions

Thanks

**Comment by lucasprag** [comment]
Btw, [this blog](http://jamesmead.org/blog/2019-09-07-using-github-actions-to-publish-a-static-site-to-github-pages) posts says I need to add a personal token for that action to work, I'm going to make it sure it's true first, but I'm going to do that.

**Comment by acant** [comment]
@lucasprag sorry about missing these comments. I was just browsing issues and saw them.
The link for middleman looks like exactly what we need.
I will have a look at it, but I also just made you and admin on this repo if you want to give it a try.

**Comment by lucasprag** [comment]
Awesome, this is the next thing I'm going to work on, thanks @acant =)

**Comment by lucasprag** [comment]
I just finished building the Github action to build the website when we push to master. 🎉 

I also fixed the problem that was removing the domain after deploy by copying the CNAME file to inside of the `build` directory.

Thanks 👍
