### ISSUE TITLE
Use https on kwruby.ca

### ISSUE THREAD

**Issue by lucasprag** [kwruby/kwruby.ca#38]
Hi @acant 

There is an option on github to use `https`.

### steps to do it
- go to the settings of this repository
- scroll to the `GitHub Pages` section
- remove the custom domain and add it back right after
- you can also enforce `https` so any `http` request will be redirected to `https`

This is a screenshot showing the section github pages section using `https`:

<img width="775" alt="github pages" src="https://user-images.githubusercontent.com/2293178/52690397-89973c80-2f2b-11e9-8707-2bd9033e78ea.png">

Please let me know if I'm missing something.

Thanks =)

**Comment by acant** [comment]
I just had to re-deploy to update the Linkedin href, but it seems that I need to make some updates to the domain. I will try to that that when I have a chance.
https://help.github.com/articles/troubleshooting-custom-domains/#https-errors

Thanks for collecting the details!

**Comment by lucasprag** [comment]
Yeah, we are secure now 👍 

![Screen Shot 2020-02-07 at 11 44 09 AM](https://user-images.githubusercontent.com/2293178/74047963-353c6680-499f-11ea-918d-7116a535ddfe.png)
